name: Test CI

on:
  - pull_request
jobs:
  test:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git status
          git remote show origin
          cat README.md