name: Release CI

on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          SUPER_SECRET: ${{ secrets.TEST }}
        run: |
          echo "$SUPER_SECRET" | base64