name: Release CI

on:
  - workflow_dispatch
  - push
jobs:
  prepare:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') && startsWith(github.ref, 'refs/heads/release-') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b workflow-$GITHUB_RUN_ID
          versionSnapshot=`grep 'version=' gradle.properties | sed 's/version=\([^-]*\)/\1/'`
          versionRelease=`echo $versionSnapshot | sed 's/\([^-]*\)-SNAPSHOT/\1/'`
          versionSnapshotNext=`echo $versionSnapshot | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e'`
          echo "$versionSnapshot -> $versionRelease  -> $versionSnapshotNext"
          sed -i "s/version=$versionSnapshot/version=$versionRelease/" gradle.properties
          git commit -am "[skip-ci] Generate release version"
          sed -i "s/version=$versionRelease/version=$versionSnapshotNext/" gradle.properties
          git commit -am "[skip-ci] Generate next snapshot version"
          git push origin HEAD 
  build_java:
    if: ${{ always() && !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - run: ./gradlew -p java :java:deltix-value-types:jar
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: java/main/build/libs/
  test_java_7:
    if: ${{ always() && !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: build_java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - run: ./gradlew -p java :java:deltix-value-types-test7:test
  test_java_8:
    if: ${{ always() && !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: build_java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - run: ./gradlew -p java :java:deltix-value-types-test8:test
  test_java_11:
    if: ${{ always() && !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: build_java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.11
    - run: ./gradlew -p java :java:deltix-value-types-test11:test  
  test_java_7_dfp:
    if: ${{ always() && !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: build_java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - run: ./gradlew -p java :java:deltix-value-types-test7-dfp:test
  test_java_8_dfp:
    if: ${{ always() && !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: build_java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - run: ./gradlew -p java :java:deltix-value-types-test8-dfp:test
  test_java_11_dfp:
    if: ${{ always() && !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: build_java
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.11
    - run: ./gradlew -p java :java:deltix-value-types-test11-dfp:test
  release:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') && startsWith(github.ref, 'refs/heads/release-') }}
    needs: 
        - test_java_7
        - test_java_8
        - test_java_11
        - test_java_7_dfp
        - test_java_8_dfp
        - test_java_11_dfp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout -b workflow-$GITHUB_RUN_ID origin/workflow-$GITHUB_RUN_ID~1
          versionRelease=`grep 'version=' gradle.properties | sed 's/version=\([^-]*\)/\1/'`
          echo $versionRelease
          git tag $versionRelease
          git push origin origin/workflow-$GITHUB_RUN_ID:$GITHUB_REF
  publish_java:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') && startsWith(github.ref, 'refs/heads/release-') }}
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - run: ./gradlew build
    - run: ./gradlew upload
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        MAVEN_SNAPSHOT_URL: https://oss.sonatype.org/content/repositories/snapshots
        MAVEN_RELEASE_URL:  https://oss.sonatype.org/service/local/staging/deploy/maven2
  cleanup:
    if: ${{ always() && !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: 
      - publish_java
    runs-on: ubuntu-latest
    continue-on-error: ${{ !startsWith(github.ref, 'refs/heads/release-') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push origin --delete workflow-$GITHUB_RUN_ID || true